include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  plugins:
    - custom_lint

linter:
  rules:
    # Code style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    unnecessary_this: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    always_declare_return_types: true
    avoid_print: true
    prefer_final_in_for_each: true
    avoid_empty_else: true
    file_names: true
    constant_identifier_names: false

    # Readability
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    avoid_returning_null: true
    prefer_interpolation_to_compose_strings: true
    lines_longer_than_80_chars: false
    omit_local_variable_types: false

    # Errors & safety
    avoid_dynamic_calls: true
    avoid_types_as_parameter_names: true
    no_leading_underscores_for_local_identifiers: true
    prefer_typing_uninitialized_variables: true
    unnecessary_null_checks: true

    # Recommended naming
    camel_case_types: true
    non_constant_identifier_names: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    source-lines-of-code: 150
    maximum-nesting-level: 5
    technical-debt: 20

  rules:
    - member-ordering
    - always-remove-listener
    - avoid-global-state
    - avoid-non-null-assertion
    - avoid-unnecessary-setstate
