name: visu
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  flutter_markdown: ^0.7.1
  flutter_svg: ^1.1.0
  video_player: ^2.5.1
  http: ^0.13.6
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  custom_lint: ^0.5.5
  dart_code_metrics: ^5.7.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/icons/
    - assets/videos/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
